# Data Science Numpy & CSV's

## Tasks Today:

1) <b>Numpy</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Python List Comparison <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) In-Class Exercise #1 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Creating an NDArray <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.array() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.zeros() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.ones() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.arange() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Making Lists into NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Performing Calculations on NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Summation <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Difference <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Multiplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) Numpy Subsetting <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Multi-dimensional Arrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Indexing NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Checking NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; j) Altering NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; k) Checking the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; l) Altering the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; m) In-Class Exercise #2 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; n) Complex Indexing & Assigning <br>
 &nbsp;&nbsp;&nbsp;&nbsp; o) Elementwise Multplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp; p) np.where() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; q) Random Sampling <br>

2) <b>Working With CSV's</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Imports <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Reading a CSV <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Loading a CSV's Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Checking Number of Records <br>
 
3) <b>Exercises</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) #1 - Calculate BMI with NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) #2 - Find the Average Sum of Marathon Runners <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) #3 - Random Matrix Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) #4 - Comparing Boston Red Sox Hitting Numbers <br>

## Numpy <br>

<p>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.</p>
<ul>
    <li>Shape = Rows & Columns</li>
    <li>Matrix = Entire Array</li>
    <li>Vector = Variables to be applied (same vector as the one used in physics)</li>
    <li>Array = Similar to lists</li>
</ul>

#### Python List Comparison

<p>Lists are flexible, dynamic python objects that do their job quite well. But they do not support some mathematical operations in an intuitive way. Consider the summation of two lists, $l_1$ and $l_2$</p>

In [2]:
# create two lists and sum both of them together (results may not be what you expect)
l_1 = [1,2,3]
l_2 = [4,5,6]

l_1 + l_2
l_1 - l_2

# what if we want l_1 + l_2 = [5, 7, 9]

TypeError: unsupported operand type(s) for -: 'list' and 'list'

<p>If we wanted to sum lists elementwise, we could write our own function that does the job entirely within the framework of python</p>

#### In-Class Exercise #1 - Write a function that sums the indexes of two lists <br>
<p>Ex: [2, 3, 4] + [1, 5, 2] = [3, 8, 6]</p>

In [3]:
# input: two lists
# output: one list where indexes are the sum of the same numbered indexes of the input lists

def sumlists(l1, l2):
    ans = []
    for i in range(len(l1)):
        ans.append(l1[i] + l2[i])
    return ans

sumlists(l_1, l_2)

[5, 7, 9]

#### Importing

In [4]:
# always import as np, standard across all of data science
!pip install numpy
import numpy as np

#### Creating an NDArray <br>
<p>NumPy is based around a class called the $\textit{NDArray}$, which is a flexible vector / matrix class that implements the intuitive matrix and vector arithmatic lacking in basic Python. Let's start by creating some NDArrays:</p>

###### - np.array()

In [15]:
arr1 = np.array([2, 4, 6])
arr2 = np.array([1, 7, 11])
strarr = np.array(['fox', 'turtle', 'lion'])
print(arr1, type(arr1))
print(arr2, type(arr2))
print(strarr, type(strarr))


[2 4 6] <class 'numpy.ndarray'>
[ 1  7 11] <class 'numpy.ndarray'>
['fox' 'turtle' 'lion'] <class 'numpy.ndarray'>


###### - np.zeros()

In [11]:
## Shape -- np.zeros() has a parameter of "shape" that must be given
arr0 = np.zeros((3, 2))
print(arr0, type(arr0))
arr0[2][1]

[[0. 0.]
 [0. 0.]
 [0. 0.]] <class 'numpy.ndarray'>


0.0

###### - np.ones()

In [17]:
arr_ones = np.ones((3,2), int)
print(arr_ones)


# notice no dots after the numbers, because we specified the datatype to be integer

[[1 1]
 [1 1]
 [1 1]]


###### - np.arange()

In [19]:
# same as python range function
# NDArray of odd numbers between 1 and 100
arr1100 = np.arange(1, 101, 2)
arr1100

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

###### - Making Lists into NDArrays

In [21]:
animals = ['fennec fox', 'orca', 'tibetan fox', 'alpaca']
NDanimals = np.array(animals)
NDanimals

array(['fennec fox', 'orca', 'tibetan fox', 'alpaca'], dtype='<U11')

#### Performing Calculations on NDArrays

###### - Summation

In [23]:
print(arr1, arr2)
arr1 + arr2

[2 4 6] [ 1  7 11]


array([ 3, 11, 17])

###### - Difference

In [24]:
print(arr1, arr2)
arr1-arr2

[2 4 6] [ 1  7 11]


array([ 1, -3, -5])

###### - Multiplication

In [25]:
print(arr1, arr2)
arr1*arr2

[2 4 6] [ 1  7 11]


array([ 2, 28, 66])

###### - Division

In [26]:
print(arr1, arr2)
arr1/arr2

[2 4 6] [ 1  7 11]


array([2.        , 0.57142857, 0.54545455])

#### Modulo

In [30]:
print(arr1, arr2)
result_mod = arr1%arr2

[2 4 6] [ 1  7 11]


#### Floor Division

In [28]:
print(arr1, arr2)
arr1//arr2

[2 4 6] [ 1  7 11]


array([2, 0, 0], dtype=int32)

#### Numpy Subsetting

In [48]:

# where is arr1 evenly divisible by arr2?
# answer:
result = np.arange(3, 48)
print('original arr: ', result, '\n')
print('boolean check returning true/false', result%2 == 0, '\n') # new NDarray containing true/false for each index in the original

# needs a fix - designed to check the first letter of each name, is actually only checking the first name
#test_ndStrings = np.array(['Bob','Mark','Angelica','Barb'])
#print(test_ndStrings[test_ndStrings[0] == ''])

# conditioal check, returns true or false
# print(arr1 < 2)
# print(arr2 >= 2)

# conditional check, that returns the elements that meet the given condition
print('actually return a subset that meets a condition:')
print(result[result%2 == 0]) # filtering our original NDarray by the condition

print(result) # subsetting is an out of place algorithm - original 'result' is not modified

original arr:  [ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47] 

boolean check returning true/false [False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False] 

actually return a subset that meets a condition:
[ 4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]


#### Multi-dimensional Arrays <br>
<p>NumPy seamlessly supports multidimensional arrays and matrices of arbitrary dimension without nesting NDArrays. NDArrays themselves are flexible and extensible and may be defined with such dimensions, with a rich API of common functions to facilitate their use. Let's start by building a two dimensional 3x3 matrix by conversion from a nested group of core python lists $M = [l_0, l_1, l_2]$:</p>

In [49]:
aList = [0,1,2]
bList = [3,4,5]
cList = [6,7,8]

# first step: convert lists into a Matrix
M = [aList, bList, cList]


# second step: place Matrix inside NDArray
ND_M = np.array(M)
ND_M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Indexing NDArrays <br>
<p> Similar to lists within lists; however, the syntax looks more like C programming language.... It is [1, 2] to access the second row, third element.</p>

In [53]:
# row,column
print(ND_M[0, 0])

# or the normal double bracket notation
print(ND_M[1][1])

0
4


#### Assigning Values in NDArrays

In [59]:
ND_M[0, 0] = 4.254651
print(ND_M)
print(ND_M.dtype) # if we try to add a float to an int32 array, we'll just get the int32 conversion of the float

[[4 1 2]
 [3 4 5]
 [6 7 8]]
int32


<p>Notice above how we ended up with a 1 in the target element's place. This is a data type issue. The .dtype() method is supported by all NDArrays, as well as the .astype() method for casting between data types:</p>

#### Checking NDArray Type

In [60]:
# usind the .dtype attribute
ND_M.dtype


dtype('int32')

#### Altering NDArray Type

In [61]:
# convert ND_M from int32 to float32
# out of place
float_ND_M = ND_M.astype(np.float32)
float_ND_M

array([[4., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float32)

In [63]:
# Checking the Shape of the ND_M Numpy Array
# Using the attribute .shape
ND_M.shape
# tuple: (rows, columns)

(3, 3)

#### Checking the Shape <br>
<p>The behavior and properties of an NDArray are often sensitively dependent on the $\textit{shape}$ of the NDArray itself. The shape of an array can be found by calling the .shape method, which will return a tuple containing the array's dimensions:</p>

In [64]:
 # shape is always rows x columns
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape
shapereturn = ND_M.shape
print(type(shapereturn))

<class 'tuple'>


#### Altering the Shape <br>
<p>As long as the number of elements remains fixed, we can reshape NDArrays at will:</p>

In [70]:
# Change the shape of the numpy array
# Using the method .reshape()

# The reshape should be a multiple of the original shape
# Meaning we can have a shape of (1,9) or (9,1) or (3,3)

# (9,1) == 9 rows , 1 column
# (1,9) == 1 column, 9 rows

print(ND_M, '\n')
print(ND_M.reshape(1,9), '\n')
print(ND_M.reshape(9,1), '\n')

[[4 1 2]
 [3 4 5]
 [6 7 8]] 

[[4 1 2 3 4 5 6 7 8]] 

[[4]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]] 



In [72]:
# keep in mind that the shape numbers do matter, (9, 1) is different than (1, 9)
x19 = ND_M.reshape(1,9)
x91 = ND_M.reshape(9,1)

print(x19[0,5])
print(x91[5,0])

5
5


#### In-Class Exercise #2 - Create a matrix of range 0 up to 16 and reshape it into a 4x4 matrice

In [75]:
"""
OUTPUT
    array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
"""
# python range, np.array(), np.reshape()
fourxfour = np.array(range(0,16)).reshape(4,4)
fourxfour
# np.arange(), np.reshape()
fourx4 = np.arange(0,16).reshape(4,4)
fourx4


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Complex Indexing & Assinging

In [90]:
print('Setting up matrix:')
print('Before assignment: all zeros:')
M = np.zeros((6,6))
print(M)
print('\n')

# remember bracket comma notation M[row, column]
# except with complex indexing and assignment, we're essentially replacing row and column with a slice
# M[rowstart:rowend, columnstart:columnend]

# Set every first element in each row to 1
M[:,0] = 1
print('After assignment of 1 to first column:')
print(M)
print('\n')

# Set all elements in rows 3 to 5 (Excluding 5) to be equal to the number 5
M[3:5, :] = 5
print('After assigning 5 to rows 3-5 not including 5:')
print(M)
print('\n')

# Set all elements in rows 3 to 5 (Excluding 5) to be equal to the number 2 excluding first and last columns
# Set the second and third columns to a number == 2
M[3:5, 1:5] = 2
print('After assigning 2 to rows 3-5 not including 5 or first/last columns:')
print(M)
print('\n')

# reset the matrix back to 0
M *= 0
print('After reset:')
print(M)
print('\n')

# Creating a vector in numpy
v = np.arange(6)
print('vector', v)
print('\n')


# Set the first row to that range of vector numbers we just created
M[0, :] = v
print('After assigning vector v to row 0 of matrix M:')
print(M)
print('\n')

# set the bottom corner of my matrix M to be the 4x4 matrix created in our exercise
fourx4 = np.arange(0,16).reshape(4,4)

M[2:, 2:] = fourx4
print('After assigning matrix fourx4 to the bottom corner of matrix M:')
print(M)

#################
# M[rows,columns]
#################

Setting up matrix:
Before assignment: all zeros:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


After assignment of 1 to first column:
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


After assigning 5 to rows 3-5 not including 5:
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [1. 0. 0. 0. 0. 0.]]


After assigning 2 to rows 3-5 not including 5 or first/last columns:
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [5. 2. 2. 2. 2. 5.]
 [5. 2. 2. 2. 2. 5.]
 [1. 0. 0. 0. 0. 0.]]


After reset:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


vector [0 1 2 3 4 5]


After assigning vector v to row 0 of matrix M:
[[0. 1. 2. 3. 4. 5.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 

#### Elementwise Multiplication

<p>As long as the shapes of NDArrays are 'compatible', they can be multiplied elementwise, broadcasted, used in inner products, and much much more. 'Compatible' in this context can mean compatible in the linear algebraic sense, i.e. for inner products and other matrix multiplication, or simply sharing a dimension in such a manner that broadcasting 'makes sense'. Here are some examples of this:</p>

In [101]:
# Initialize a vector of range 6, then reset Matrix to zero and run vector multiplication on the matrix
v61 = np.arange(6).reshape(6,1)
v16 = np.arange(6)
M[0, :] = 0
print(M, v)

print(M*v61)
print(M*v16)

# Reset the Matrix to 0


[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  2.  3.]
 [ 0.  0.  4.  5.  6.  7.]
 [ 0.  0.  8.  9. 10. 11.]
 [ 0.  0. 12. 13. 14. 15.]] [[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  4.  6.]
 [ 0.  0. 12. 15. 18. 21.]
 [ 0.  0. 32. 36. 40. 44.]
 [ 0.  0. 60. 65. 70. 75.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  3.  8. 15.]
 [ 0.  0.  8. 15. 24. 35.]
 [ 0.  0. 16. 27. 40. 55.]
 [ 0.  0. 24. 39. 56. 75.]]


#### np.where() <br>
<p>If statement within NDArrays that allows you to run conditionals on the entire array</p>

In [109]:
new_array = np.array(range(10,401, 10)).reshape(4,10)
print(new_array)
print('\n')
print('Get the locations of numbers divisible by 20')
np.where(new_array%20==0) # where is returning two vectors- one of row numbers and one of column numbers
# Transform Data based on boolean mask == True

x = new_array[np.where(new_array%20==0)].reshape(4,5) # subsetting
print(x)

new_array[np.where(new_array%20==0)] = 0 
# using np.where() for complex assignment can be especially helpful for cleaning data
print(new_array)

[[ 10  20  30  40  50  60  70  80  90 100]
 [110 120 130 140 150 160 170 180 190 200]
 [210 220 230 240 250 260 270 280 290 300]
 [310 320 330 340 350 360 370 380 390 400]]


Get the locations of numbers divisible by 20
[[ 20  40  60  80 100]
 [120 140 160 180 200]
 [220 240 260 280 300]
 [320 340 360 380 400]]
[[ 10   0  30   0  50   0  70   0  90   0]
 [110   0 130   0 150   0 170   0 190   0]
 [210   0 230   0 250   0 270   0 290   0]
 [310   0 330   0 350   0 370   0 390   0]]


#### Random Sampling <br>
<p>NumPy provides machinery to work with random numbers - something often needed in a broad spectrum of data science applications.</p>

In [125]:
# np.random.uniform()

# A single call generates a single random number between 0 and 1

print('Here is a random number: %s' % np.random.uniform())

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.uniform(0, 1e6))

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.uniform(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 3x3 matrix with numbers between 0 and 10: \n %s' % np.random.uniform(0, 10, (3, 3)))

# integers: randint()
print(f'Here is a random integer between 0 and 100: \n {np.random.randint(0, 101)}')

Here is a random number: 0.5970564797928954
Here is a random number between 0 and 1 Million: 557356.9092324637
Here are 5 random numbers between 0 and 10: [4.97601808 6.29671075 0.3505931  0.21602149 9.90581082]
Here is a 3x3 matrix with numbers between 0 and 10: 
 [[4.37170745 1.5247371  3.53751885]
 [4.93501616 2.34181788 1.76016558]
 [7.06337532 4.59465505 0.20544477]]
Here is a random integer between 0 and 100: 
 62


## Working With CSV's

#### Imports

In [1]:
import csv
import numpy as np
from datetime import datetime

#### Reading a CSV

In [8]:
# Creating Function to open and read CSV data
# essentially we can open a file in the background of python, read that file, and then close it once its been read

def open_csv(filename, delimiter=','):
    # define an empty list in which to store our data
    data = []
    # built-in open within a with block
    with open(filename, encoding='utf-8') as mData:
        # use the csv module reader method to create a list
        oData = csv.reader(mData, delimiter=delimiter)
        
        # loop over whats in the csv.reader and add that row by row to the data list
        for row in oData:
            data.append(row)
    
    return data

csv_data = open_csv('../files/redsox_2017_hitting.txt')
print(csv_data[-1])

['23', '2B', "Chase d'Arnaud", '30', '2', '1', '1', '2', '1', '0', '0', '0', '0', '0', '0', '0', '0', '1.000', '1.000', '1.000', '2.000', '428', '1', '0', '0', '0', '0', '0']


#### Loading a CSV's Data 

In [16]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

# i = integer, f = float, |s25 = string with 25 characters
DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

# instead of loading csv normally, let's load it into a numpy array to calculate results on
sox2017 = np.genfromtxt('../files/redsox_2017_hitting.txt', delimiter=',', skip_header=1, usecols=np.arange(28), invalid_raise=False, names=FIELDS, dtype=DATATYPES)
#print(sox2017)

# access all the values in the names column - can kind of treat this like a python dictionary when it comes to the column names
names = sox2017['Name']
#print(names)

# total home runs
total_hr = sum(sox2017['HR'])
print(total_hr)

168


#### Summing the top 5 hitters for HR's

In [28]:
# find the top 5 hr hitters

# Step 1: Get all HR data into a variable
# Step 2: Get all Player Names
# Step 3: Create new list for new_names (empty to start)
# Step 4: Decode the player names into regular strings
# Step 5: Grab all data and place inside of a zipped list
# Step 6: Sort values based on HR data

# Step 1
hrs = sox2017['HR']


# Step 2
names = sox2017['Name']


# Step 3
newnames = [x.decode('utf-8') for x in names]

# Step 4
# combined into step 3 with list comprehension

#print(newnames)

# Step 5
zipped_values = list(zip(newnames, hrs))


# Step 6
top5 = sorted(zipped_values, key= lambda x: x[1], reverse=True)[:5]
top5

hrs_from_top_5 = sum([x[1] for x in top5])
hrs_from_top_5 # 106 hrs from top 5 hr hitters

# conclusion?
# 168 total HRs
# 106 from top 5 hitters
106/168*100
# 63% of the red sox home runs in 2017 came from just 5 hitters

63.095238095238095

# Exercises To Complete.... <br>
<p>Given in separate file after completion of this file</p>